=== wowa-q/ptProjects/test/fixtures/fin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="project" type="prType" />
  <xsd:element name="transaction" type="transType" />
  <xsd:complexType name="transType">
    <xsd:sequence>
      <xsd:element name="datum" type="xsd:string" />
      <xsd:element name="value" type="xsd:float">
        <!-- 
        <xsd:attribute name="direction" type="xsd:string" />
		-->
      </xsd:element>
      <xsd:element name="type" type="xsd:string" />
      <xsd:element name="debitor" type="xsd:string" />
      <xsd:element name="verwendung" type="xsd:string" />
      <xsd:element name="konto" type="xsd:string" />
      <xsd:element name="blz" type="xsd:string" />
      <xsd:element name="debitor-id" type="xsd:string" />
      <xsd:element name="Mandatsreferenz" type="xsd:string" />
      <xsd:element name="Kundenreferenz" type="xsd:string" />
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:integer" />
  </xsd:complexType>
  <xsd:complexType name="prType">
    <xsd:sequence>
      <xsd:element ref="transaction" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== wowa-q/ptProjects/test/fixtures/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fin.xsd">
  <meta>
	<prName>Test</prName>
    <nrTransactions>2</nrTransactions>
    <lastTransaction>17.2.2019</lastTransaction>
    <firstTransaction>1.1.2019</firstTransaction>
	
  </meta>
  <transaction id="1">
    <datum>17.2.2019</datum>
    <value direction="in">20</value>
    <type>tbd</type>
    <debitor>tbd</debitor>
    <verwendung>tbd</verwendung>
    <konto>tbd</konto>
    <blz>tbd</blz>
    <debitor-id>tbd</debitor-id>
    <Mandatsreferenz>tbd</Mandatsreferenz>
    <Kundenreferenz>tbd</Kundenreferenz>
  </transaction>
  <transaction id="2">
    <datum>17.2.2019</datum>
    <value direction="in">20</value>
    <type>tbd</type>
    <debitor>tbd</debitor>
    <verwendung>tbd</verwendung>
    <konto>tbd</konto>
    <blz>tbd</blz>
    <debitor-id>tbd</debitor-id>
    <Mandatsreferenz>tbd</Mandatsreferenz>
    <Kundenreferenz>tbd</Kundenreferenz>
  </transaction>
</project>
